### ISSUE TITLE
A bug on Windows

### ISSUE THREAD

**Issue by oierwanhong** [coder3101/cp-editor#105]
**Describe the bug**
After I downloaded the file(.exe) and install it(I downloaded it by the alternative download link),it happened:[the bug](https://cdn.luogu.com.cn/upload/image_hosting/216dl3hz.png) (I used to download it again,but I also failed)

(Oh,I'm new in Github,so please pardon me...)

**Comment by ouuan** [comment]
别用洛谷图床，直接粘贴/上传就可以传到 Github 上了，https://sm.ms 也行。

![image](https://user-images.githubusercontent.com/30581822/72663389-50b1f280-3a2d-11ea-8c55-717cc0474e27.png)

请阅读 README.md 中的 FAQ:

> - I get DLL Missing error while launching the application?
>   - Please download [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by oierwanhong** [comment]
Oh...I made a silly mistake.Thanks a lot.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ouuan"; 
发送时间: 2020年1月18日(星期六) 晚上8:02
收件人: "coder3101/cp-editor";
抄送: "oierwanhong"<2522943959@qq.com>;"Author";
主题: Re: [coder3101/cp-editor] A bug on Windows (#105)




别用洛谷图床，直接粘贴/上传就可以传到 Github 上了，https://sm.ms 也行。
 

 
请阅读 README.md 中的 FAQ:
   
I get DLL Missing error while launching the application?  
Please download Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019.
  
   
&mdash;
