### ISSUE TITLE
Issue when submitting problem during the contest

### ISSUE THREAD

**Issue by nikhil-sarda** [coder3101/cp-editor#111]
**Describe the bug**
I have faced this issue twice.Everything else is working fine but when submitting the problem ,during the contest ,it replies back to select the problem.Please see if it can be corrected or we'll have to live with it (This never happened when I am practicing problems).

**To Reproduce**
Submit a problem during the contest.

**Expected behavior**
It should have got submitted and AC verdict.

**Screenshots**

![Screenshot (7)](https://user-images.githubusercontent.com/51774873/72694294-87d1f200-3b5a-11ea-9063-d3bebf7f4b92.png)

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
  N/A

**Additional context**
N/A

**Comment by ouuan** [comment]
Try submitting to <http://codeforces.com/contest/1293/problem/A> instead of <http://codeforces.com/contest/1293/problem/0>. (It says "Submit 1293 0", and CF opens `problem/0` when the contest begins, I guess that causes the bug.)

If it's able to submit to `problem/A` but not `problem/0`, I'd either fix this bug in CP Editor or open an issue in CF Tool.

**Comment by nikhil-sarda** [comment]
> Try submitting to http://codeforces.com/contest/1293/problem/A instead of http://codeforces.com/contest/1293/problem/0. (It says "Submit 1293 0", and CF opens `problem/0` when the contest begins, I guess that causes the bug.)
> 
> If it's able to submit to `problem/A` but not `problem/0`, I'd either fix this bug in CP Editor or open an issue in CF Tool.

This is right.I just checked with the url changing and it was not getting submitted for '/0' but got sumbmitted when i did it for '/A'.Please change it in the CP Editor as soon as possible.

Waiting for the next update .Thanks in advance.

**Comment by testitem** [comment]
@nikhil-sarda Technically, it is Codeforces' problem for opening it on `/0`, but I guess you need to do a special case check in cftool.

**Comment by nikhil-sarda** [comment]
> @nikhil-sarda Technically, it is Codeforces' problem for opening it on `/0`, but I guess you need to do a special case check in cftool.

I don't have any idea how to do that.It may be helpful if you suggest ways to do it,i mean,how should I do a special case check in cftool.
