### ISSUE TITLE
CFtool not working in the latest version

### ISSUE THREAD

**Issue by nikhil-sarda** [coder3101/cp-editor#112]
**Describe the bug**
I just installed the latest version 5.3.1.Its showing that cftool will not work as it is not installed or not on system path.I tried on cmd "cf --version" and its working fine there so its in the system path.
(I have also tried rebooting).What should I do now?

**To Reproduce**
Parse any problem on codeforces.The error is shown.

**Expected behavior**
Submit option should have worked.

**Screenshots**
![Screenshot (10)](https://user-images.githubusercontent.com/51774873/72857176-d611fd00-3ce2-11ea-92d8-1e715eee0aab.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by coder3101** [comment]
@nikhil-sarda Is this issue still bugging you?

**Comment by coder3101** [comment]
I know that this could happen, When I was first setting up cf it happened to me as well, cmd says CF was on path but editor didn't caught it.

**Comment by nikhil-sarda** [comment]
> I know that this could happen, When I was first setting up cf it happened to me as well, cmd says CF was on path but editor didn't caught it.

Yes.

**Comment by ouuan** [comment]
> @nikhil-sarda Is this issue still bugging you?

The fix hasn't come into release yet.
