### ISSUE TITLE
Unexpected compile error: No such file or directory

### ISSUE THREAD

**Issue by nikhil-sarda** [coder3101/cp-editor#113]
**Describe the bug**
I thought I would give today's contest perfectly using the best editor I found so far.But it doesn't seem so.New version has come with errors I guess.
And now I clicked on compile and run and again an unexpected error ,This wasn't happening before installing this one(v5.3.1)
Please mention how I should fix this if it's my computer's problem.I also tried saving the code but its still showing this.

![Screenshot (11)](https://user-images.githubusercontent.com/51774873/72860729-ba602400-3ced-11ea-9232-1e5e5e965be9.png)
. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ouuan** [comment]
Is the error message the same after saving the file? (Still `Sarda/AppData/Local/Temp/CPEditor-XXXXXX/sol.cpp` ?)

**Comment by nikhil-sarda** [comment]
> Is the error message the same after saving the file? (Still `Sarda/AppData/Local/Temp/CPEditor-XXXXXX/sol.cpp` ?)

![Screenshot (13)](https://user-images.githubusercontent.com/51774873/72868348-cb1d9380-3d07-11ea-9f40-0b8ca7a80a97.png)

After saving in the directory...even if its there!

**Comment by ouuan** [comment]
@nikhil-sarda I'd like a screenshot with the window title.

**Comment by ouuan** [comment]
Oh, I think I got the reason.

**Comment by ouuan** [comment]
I think I got the reason.

**Comment by nikhil-sarda** [comment]
> @nikhil-sarda I'd like a screenshot with the window title.

Here it is.
![Screenshot (14)](https://user-images.githubusercontent.com/51774873/72870991-ab8a6900-3d0f-11ea-9ddc-4c2da44a7aab.png)

**Comment by nikhil-sarda** [comment]
> I think I got the reason.

Am i to do something or its from your side?

**Comment by ouuan** [comment]
It's about the space in the path, I'll fix it soon.

**Comment by nikhil-sarda** [comment]
Thanks and sorry if I had been rude ,as i was really unhappy with it.

**Comment by ouuan** [comment]
You should complete the issue template and use a meaningful title, everything else are fine.

**Comment by nikhil-sarda** [comment]
> It's about the space in the path, I'll fix it soon.

How will I know when a new updated version will be released?

**Comment by ouuan** [comment]
> > It's about the space in the path, I'll fix it soon.
> 
> How will I know when a new updated version will be released?

There are two ways:

1. Watch this repo (or watch release only), the watch button should be at the top of the webpage. Check Github setting and make sure you are getting notifications from Github, too.

2. Join the [Telegram group](https://t.me/cpeditor), there will be an announcement when the release is out.

**Comment by ouuan** [comment]
Fixed via 12c18d5 and b5e9df3.

Struggled for a long time with detached run on Windows with spaces in the path.

**Comment by nikhil-sarda** [comment]
> Fixed via [12c18d5](https://github.com/coder3101/cp-editor/commit/12c18d5cd9db3a603ca1241f80a4afcf028d0050) and [b5e9df3](https://github.com/coder3101/cp-editor/commit/b5e9df34c019284c104cb13a9eeab1772187a88c).
> 
> Struggled for a long time with detached run on Windows with spaces in the path.

But how did it change in this new version,just curious to know?

**Comment by ouuan** [comment]
> > Fixed via [12c18d5](https://github.com/coder3101/cp-editor/commit/12c18d5cd9db3a603ca1241f80a4afcf028d0050) and [b5e9df3](https://github.com/coder3101/cp-editor/commit/b5e9df34c019284c104cb13a9eeab1772187a88c).
> > Struggled for a long time with detached run on Windows with spaces in the path.
> 
> But how did it change in this new version,just curious to know?

Add quotes for arguments, you can read the codes by yourself.
