### ISSUE TITLE
Issues on Mac

### ISSUE THREAD

**Issue by testitem** [coder3101/cp-editor#116]
**Describe the bug**
Several bugs:

 1. Everything is extremely low-resolution and blurry.
 2. It's globally dark, which I thought was both deprecated and removed.
 3. I can go into "full screen", in which the test case text boxes suddenly thin themselves (#88 fix?) but every time I click something the window suddenly exits full-screen.
 4. My compiler is g++-8, but when I set that, it's reported as invalid compiler command. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs Mojave
 - Browser
 - Version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by testitem** [comment]
I vote that @caretaker-claire is ~~re****ed~~ useless and should be removed.

**Comment by ouuan** [comment]
Generally, I'm not able to test on Mac, so maybe I can't help you much.

1. What's your screen's resolution?

2. Is your system theme dark? (Is other windows on your system dark?)

3. How did it report that g++-8 is invalid?

**Comment by ouuan** [comment]
BTW, how does "Reveal in Finder" in the context menu (displays when right-clicking the tab bar) work? Does it open the Finder and select the file? Does it work properly when the path contains spaces?

**Comment by coder3101** [comment]
> 
> 
> I vote that @caretaker-claire is ~re****ed~ useless and should be removed.

It may be annoying but makes our life, less annoying by asking all details for issues, otherwise people are more retarded and they open issues like "This is not working, that is not working", giving no information about OS, version and other contexts that may help us. plus there are other good things she does, open a PR, it notifies me about it. Github does not notify this.

**Comment by coder3101** [comment]
>     1. Everything is extremely low-resolution and blurry.

This is confirmed, one of other person reported this to me on codeforces

**Comment by coder3101** [comment]
I will check it on mac. I wish to produce a Bundle.dmg for mac as well, expect some progress by the end of this weekend

**Comment by testitem** [comment]
@ouuan I am on a MacBook Pro Retina 2015. It says the resolution is 2560 x 1600, and my system is set to default resolution. Yes, my system theme is dark. However I don't expect it to affect Qt, since most windows on my Mac don't care about the system theme, which makes me wonder what the point of it is

It reported invalidness with

```
[20:00:23] [Compiler] [Compiler command for Cpp is invalid. Is compiler on PATH?]
```

For example, when I go into fullscreen, this is what it shows:
<img width="1280" alt="Screen Shot 2020-01-24 at 8 01 11 PM" src="https://user-images.githubusercontent.com/19212916/73067726-653a3300-3ee4-11ea-9365-88a0e2839e61.png">

But when I go to CPEditor -> Preferences -> OK, it suddenly blurs itself, shrinks, and becomes this:
<img width="1215" alt="Screen Shot 2020-01-24 at 8 01 49 PM" src="https://user-images.githubusercontent.com/19212916/73067727-65d2c980-3ee4-11ea-9c78-870cfc00785e.png">

**Comment by testitem** [comment]
Also, the test case textboxes are ridiculously wide on Mac. It definitely should be thinner.

**Comment by testitem** [comment]
Ok, I upgraded to the new version on the dev branch, and I get this:

<img width="1215" alt="Screen Shot 2020-01-25 at 10 34 07 AM" src="https://user-images.githubusercontent.com/19212916/73115259-a707bf80-3f5e-11ea-9af7-0d49918fe250.png">

**Comment by testitem** [comment]
It seems that the master branch works. But the window size on Mac is very different than on Linux. The length to width ratio is something like 16 to 49 instead of 16 to 25... :|

**Comment by ouuan** [comment]
@testitem How much can you adjust the width ratio? It can be adjusted by dragging.

**Comment by ouuan** [comment]
> Ok, I upgraded to the new version on the dev branch, and I get this:
> 
> <img alt="Screen Shot 2020-01-25 at 10 34 07 AM" width="1215" src="https://user-images.githubusercontent.com/19212916/73115259-a707bf80-3f5e-11ea-9af7-0d49918fe250.png">

There were no tabs. You should open a tab by yourself. See #115 also.

**Comment by ouuan** [comment]
But where are the menus?

![image](https://user-images.githubusercontent.com/30581822/73117023-c90f3b00-3f7a-11ea-8457-e9d3ae8fa418.png)

**Comment by testitem** [comment]
Dev branch works now. But can the "screen erratically resizing" issue be fixed? In particular, the window doesn't like it when I'm in full screen - i.e. if I go to Preferences -> OK then it suddenly moves out of full screen. It seems that in full screen the test case boxes get narrower.

I actually can't adjust the width ratio in other ways than going into full screen.

please make the test case boxes narrower, like at least 5 times narrower

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/19212916/73117374-a59abf00-3f7f-11ea-9c10-11db617ad6e6.png">

**Comment by coder3101** [comment]
Okay, I am giving another try to minimize those boxes. I don't get why won't they get smaller. Let;s do some hit and try brute force. So many people have reported it. I will do it on master and dev should be rebased on master @ouuan, Some Quality of Life improvements have been made there.

**Comment by coder3101** [comment]
> It's globally dark, which I thought was both deprecated and removed.

Its because your mac theme does it looks like it. Its Apple the same on KDE, if you use dark theme in system the system automatically changes the stylesheets of all the Qt apps and makes them dark.

**Comment by coder3101** [comment]
> Everything is extremely low-resolution and blurry.

I have seen many reports for Qt being blurry on Retina Display. This requires some info.plist hack, which can be done only if I package it into dmg. For the moment please bear with this negligible issue.

**Comment by coder3101** [comment]
> My compiler is g++-8, but when I set that, it's reported as invalid compiler command.

strange, I will have to get a mac machine for this to investigate, maybe something prevents CP Editor from accessing your Environment, Environment is required for Editor to recognize the compiler. Maybe you could try to provide the complete path of compiler to preferences like `/usr/bin/gcc-8` or wherever the compiler is.

**Comment by coder3101** [comment]
> I can go into "full screen", in which the test case text boxes suddenly thin themselves (#88 fix?) but every time I click something the window suddenly exits full-screen.

Could you give the current `dev` branch a try and reproduce the same.

**Comment by coder3101** [comment]
The editor now can get this small, even will fit on 200x300 pixel displays.
![img](https://i.imgur.com/IGHkaku.jpg)

Input boxes can get very narrow now. Just see!
![img](https://i.imgur.com/SCYPeKQ.jpg)

**Comment by coder3101** [comment]
All changes to `dev` branch.

**Comment by coder3101** [comment]
> I will do it on master and dev should be rebased on master @ouuan, Some Quality of Life improvements have been made there.

You can ignore this, I have done it already

**Comment by ouuan** [comment]
@testitem So is the only issue "Everything is extremely low-resolution and blurry." now?

**Comment by coder3101** [comment]
> @testitem So is the only issue "Everything is extremely low-resolution and blurry." now?

I believe this is fixed too, let him try the new DMG if he believes this issue remains he can re/open issue
