### ISSUE TITLE
Doesn't find cf-tool installation

### ISSUE THREAD

**Issue by testitem** [coder3101/cp-editor#121]
**Describe the bug**
I installed the cf-tool `cf` binary in `/usr/local/bin`. However, cpeditor reports that it can't find it:

```
[20:17:59] [CFTools] [You will not be able to submit code to Codeforces because CFTools is not installed or is not on SYSTEM PATH]
```

```
~ mac$ which cf
/usr/local/bin/cf
```

However, on Linux, when I put `cf` in `/usr/bin`, it (used to) work perfectly fine.

**To Reproduce**

**Expected behavior**
Work

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ouuan** [comment]
What does `cf --version` return? (The return value can be checked by `cf --version; echo $?` on Linux.)

**Comment by testitem** [comment]
1. ```
~ mac$ cf --version
Codeforces Tool (cf) v0.8.2
```
2. real 0.009 seconds

3. yes

**Comment by ouuan** [comment]
I mean the return value rather than the output.

**Comment by ouuan** [comment]
If you are using the latest version (no matter on master or on dev), and `cf --version` returns `0` with 2 seconds, I have no idea what's going on. Since you are already compiling from source, you can debug by yourself.

**Comment by testitem** [comment]
0, which means there is no error.

**Comment by testitem** [comment]
Btw, I think this happens with g++-8 too. When I set `g++-8 -Wall` as the compile command, it said something along the lines of "invalid: can't find in path", but when I set it as `/usr/local/bin/g++-8 -Wall`, it worked perfectly fine.

However, `/usr/local/bin` *is* in my PATH, so the problem may originate from cpeditor only checking /usr/bin. It would be nice if we can set the cf-tool path.

**Comment by ouuan** [comment]
I just moved my `cf` to `/usr/local/bin` and after `hash cf` it works for me. (Manjaro KDE 18.1.5)

**Comment by testitem** [comment]
Running `hash cf` doesn't work.

```
[21:59:27] [CFTools] [You will not be able to submit code to Codeforces because CFTools is not installed or is not on SYSTEM PATH]
[21:59:32] [CFTools] [You will not be able to submit code to Codeforces because CFTools is not installed or is not on SYSTEM PATH]
```

**Comment by coder3101** [comment]
Hey, I will provide a way for you to choose the `cf` path yourself. It will be in settings, choose the executable in editor or maybe make it available inside the installation directory itself. So you don't need to download it yourself. You can have multiple cf tools one for you in `/usr/local/bin` to be used in cmd and editor will have its own in say `/applications/<some_path>/cf`. As far as I know CF shares and stores configs at one location. This will also eventually close #91 as well

**Comment by coder3101** [comment]
which one do you prefer? ability to choose path of cf.exe or let editor has its own cf.exe in `C://Program Files/CP Editor/bin/cf.exe`.

**Comment by coder3101** [comment]
I vote to let user choose the path of cf.exe

**Comment by coder3101** [comment]
This bug is preventing me from pushing a new release. In settings there should be a way to choose the path of `cf.exe` and then `QProcess` can directly run it without any false negatives. Once, it is resolved a new release will be done!
