### ISSUE TITLE
Can't click "Codeforces Tool Path" on Mac

### ISSUE THREAD

**Issue by testitem** [coder3101/cp-editor#124]
**Describe the bug**
I can't click the "Codeforces Tool Path" button to select the path in the Extras tab.

Furthermore, I think that the user should enter a full directory name (i.e. enter `/usr/local/bin/cf` into an entry box) since the `/usr` and other miscellaneous directories are hidden in the Mac finder.

**To Reproduce**
1. Go to Preferences->Extras
2. Click on "<Search on ... ent>"
3. Nothing happens

**Expected behavior**
An entry box, asking the user for the full path to cf-tool.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by testitem** [comment]
Btw I'm using the dev branch.

**Comment by coder3101** [comment]
@ouuan Could you handle this. Make user type the path

**Comment by coder3101** [comment]
Try again. Use master this should have been fixed now! If not reopen
