### ISSUE TITLE
Not able to parse contest in cp editor

### ISSUE THREAD

**Issue by shah-entrance** [coder3101/cp-editor#128]
![Screenshot (4)](https://user-images.githubusercontent.com/40912165/73277168-c4af8000-420f-11ea-9e84-8dadb7daf8c2.png)

**Comment by shah-entrance** [comment]
Also I/m not able to change the font size. Can you tell me from where I can change the font size?

**Comment by coder3101** [comment]
Preferences => Click on big button that has Font written and then it will open font chooser dialog

**Comment by shah-entrance** [comment]
Thank you :)

**Comment by coder3101** [comment]
Invalid payload is reported because [this](https://github.com/coder3101/cp-editor/blob/369d6356d30dc74d0e1994ce1f729607441d9628/src/CompanionServer.cpp#L89) if condition failed. 

It is related with what data the companion sends to editor. Could you please tell me which browser are you using?

**Comment by shah-entrance** [comment]
Google Chrome

**Comment by coder3101** [comment]
I haven't tested if it works on Chrome. By the way if you have firefox could you try that as well. Install the browser extension and use it to parse contest or problem. If that works it will give us some clue

**Comment by shah-entrance** [comment]
No, I don't have firefox, Is this feature only available with firefox?

**Comment by shah-entrance** [comment]
Okay, by the way, thank you so much to help me and reply so quickly.

**Comment by shah-entrance** [comment]
Will I be able to see the submit button only when this problem is over?

**Comment by coder3101** [comment]
> Will I be able to see the submit button only when this problem is over?

Yes and on the same version of chrome. It is working as expected

**Comment by shah-entrance** [comment]
Hey, I'm able to parse the test cases in Firefox, but not able to submit my solution.
Error : [You will not be able to submit code to Codeforces because CFTools is not installed or is not on SYSTEM PATH. You can set it manually in settings.]
But I've already installed CFtools since I can submit my solution through cf tools using cmd

**Comment by coder3101** [comment]
Preferences -> Extra -> Type path of CF.exe

**Comment by shah-entrance** [comment]
Thank you, It's working now.

**Comment by ouuan** [comment]
@shah-entrance Check the "debug mode" in competitive companion and open console (F12→Console) to see what it sent.

**Comment by shah-entrance** [comment]
It shows [Got a POST request]

**Comment by coder3101** [comment]
> It shows [Got a POST request]
He meant debug mode in Competitive companion browser extension
