### ISSUE TITLE
Make the "Expected output" tab able to thin.

### ISSUE THREAD

**Issue by testitem** [coder3101/cp-editor#136]
**Is your feature request related to a problem? Please describe.**
The test case section is far to wide on my display, but when I try to thin it like with the `master` branch, the text boxes just gets pushed off to the side, which is inconvenient, especially when the text boxes are unnecessarily wide.

**Describe the solution you'd like**
RT

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by ouuan** [comment]
4acc65a9dc3c15a71b509081dc8c12f656b5e4f8
