### ISSUE TITLE
Set up Github Actions Artifacts

### ISSUE THREAD

**Issue by testitem** [coder3101/cp-editor#143]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be useful to have cutting-edge releases automated by Github Actions, so every time the CI is done, the corresponding executables are stored as artifacts.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by ouuan** [comment]
I think that will be a great waste, users can build from source if they can't wait for the next release.

**Comment by testitem** [comment]
Isn't Github Actions free though?

**Comment by ouuan** [comment]
Are you thinking that "waste" is the waste of money?

**Comment by testitem** [comment]
I certainly don't want to recompile every time there is a new commit, because I need to reconfigure the Cmake qt path and sometimes because there are collisions in my local repository I need to re-download all of the source code. In particular, with the scintilla branch, compiling from source takes ten to twenty minutes. For public repositories, Actions is free, and space isn't going to be wasted because the artifacts are automatically deleted after 90 days.

**Comment by ouuan** [comment]
You can Google for how to set the environment variables permanently, and create a batch file for the build commands.

**Comment by coder3101** [comment]
Now you can use Artifacts of each commit. Head to GitHub Artifacts and download the zip for the your platform. You will find 2 zip for each os. One uses latest Qt and other is older Qt. (5.14.x is latest Qt). First try latest Qt then if that doesn't work then try other zip.

Inside zip you will only find the binary. (No dependency), for windows you will have .exe, you can then replace your `Program Files/CPEditor/CPEditor.exe` with the new .exe.

Same for Linux you need to edit the AppImage, download the AppImage tool for editing the AppImage and for Mac you can replace `CPEditor.app/Contents/MacOs/CPEditor` with the one in the zip.

**Comment by coder3101** [comment]
Shouldn't this be closed? @ouuan
