### ISSUE TITLE
Add `--verbose` or a machanism to trace/log all events in editor

### ISSUE THREAD

**Issue by coder3101** [coder3101/cp-editor#146]
**Is your feature request related to a problem? Please describe.**
When a user reports some bugs we have to take their word for the issue, there is no way to know what might be going on in the editor. Say for some users Competitive companion reports "Invalid Payload" and there is no way for us to find why?

**Describe the solution you'd like**
Editor should have a logging mechanism that logs all events inside editor into a log file which user can provide along with the issue so that we can have a look at it and find the issue. It would also be nice to have `--show-logs` on command line so that editor writes all logs on stdout as well.

**Describe alternatives you've considered**
There is no Alternative for this as of now. 

**Additional context**
N/A

**Comment by coder3101** [comment]
I will work on it.

**Comment by ouuan** [comment]
> // if verbose is enabled, then both log and editor errors are written to stderr
> // @ouuan : Could you make editor errors go to stdout?

But why should we put errors in stdout?

**Comment by coder3101** [comment]
Okay leave it, I will swich logs go to stdout.

**Comment by ouuan** [comment]
I'm switching log functions to QTextStream, then you'll be able to log like this:

```
Core::Log::i("head") << "this is a body" << 42;
```

The current function will remain, but `Stringify` will be removed.

**Comment by coder3101** [comment]
Good, that would be nice

**Comment by ouuan** [comment]
Why should command-line option error and log be separated?

**Comment by coder3101** [comment]
I thought it would interfere with the user interaction on cmd. If i redirect to other fd then user can redirect stderr to null or file and continue to use application normally via cmd.

**Comment by ouuan** [comment]
I suggest not redirecting to stderr even if failed to create log file.

**Comment by coder3101** [comment]
Okay so if user himself passes --verbose to cmdline. I guess this would be no harm because on cmd the application isn't interactive is it? (waits for input before doing action after launched is what i mean by interactive)

**Comment by ouuan** [comment]
It's not interactive up to now.

**Comment by coder3101** [comment]
I also think that after this feature is done, we should start putting 6.0 RC and then you can write a blog about it on CF and I have planned to create some introductory videos for YouTube and on my social sites to share.

Do you want something else to be a part of 6.0? (Obviously all features checks will be done and checked for stability)

**Comment by coder3101** [comment]
Good if it's not interactive, --verbose will not make things look bad when interactive cmd line is added. So we should avoid it.

**Comment by coder3101** [comment]
After you have improved the log system, instead of logging things, You could create a menu option in Help section named "Show logs" and it will pop open a window like preferences window, and user will have choice to pause the logs, or live logs(new logs will be updated as soon as one happens). Copy log file location to clipboard, Reveal log file in finder/explorer. [It will be good if this log window is monospace and reads from logfile directly, you could use fileWatcher or some other signal of QFile, like readReady]

 If you have time, you can work on this. I am working on logging all events and it's mammoth task!

**Comment by ouuan** [comment]
I think reveal in file manager is enough, users can see the log in other editors.

**Comment by coder3101** [comment]
Okay that will be okay as well

**Comment by ouuan** [comment]
These should be added in the preference window.

1. Enable/disable logs.
2. Set the directory to put log files.
3. Set the max number of log files to keep. Possibly infinity.
4. A button for deleting all log files.
5. A button for open log directory, reveal the current log file if possible.

This may require #166.

P.S. Logging is a big project, maybe we need a long time to finish it.

**Comment by ouuan** [comment]
I don't have much time for CP Editor, so I want to work on other things I think are more important, and I won't work on this.

**Comment by coder3101** [comment]
> I don't have much time for CP Editor, so I want to work on other things I think are more important, and I won't work on this.

Okay, I will do it slowly slowly!

**Comment by coder3101** [comment]
> 
> 
> These should be added in the preference window.
> 
>     1. Enable/disable logs.
> 
>     2. Set the directory to put log files.
> 
>     3. Set the max number of log files to keep. Possibly infinity.
> 
>     4. A button for deleting all log files.
> 
>     5. A button for open log directory, reveal the current log file if possible.
> 
> 
> This may require #166.
> 
> We should finish this first, logging other events could be a good start for new contributors.

4 and 5 are done. 1 could be a nice candidate for "new contributors". 2, Seems very unlikely as I have not seen other applications ask where to keep logs, Logs are kept in Temp always. So let's keep it that way only. Setting number of log files could also be a nice candidate for "new contributors", but I think, there is no practical application of keeping very old logs on disk. Last 50 is good enough for us now. If you feel so that it is important, You can open a issue for it.
