### ISSUE TITLE
Restructure source code

### ISSUE THREAD

**Issue by coder3101** [coder3101/cp-editor#149]
**Is your feature request related to a problem? Please describe.**
Currently all source code lies in one open directory named src. Nothing has been regrouped based on namespace or extensions.

**Describe the solution you'd like**
Put different files in different directories inside src. Like Compiler.cpp and other in a directory named src/core and similarly for include files.

**Describe alternatives you've considered**
With addition of different files and new files it will become difficult to find stuffs. Keeping things organized is a good practice

**Additional context**
Should be done only after dev has been merged to master and this changes must be done before 6.0

**Comment by testitem** [comment]
IMHO there's really not enough files to render this necessary...

**Comment by coder3101** [comment]
> IMHO there's really not enough files to render this necessary...

Yes as of now there is not enough file. But if you see at source you will find that most of the files are just too large and in coming days more and more files could be added as functionality increases. We should do this now so that when code grows we don't have to worry about it. Also, it is no big deal, just a few refactoring will be required. Its less than 2-3 minute issue but will be useful in future.
