### ISSUE TITLE
Avoid unnecessary copies, pass by const ref

### ISSUE THREAD

**Issue by coder3101** [coder3101/cp-editor#151]
**Is your feature request related to a problem? Please describe.**
At many places the functions take things as copy and this adds to performance. In functions where it is possible to have pass by const references should take argument by const ref. Most of such cases are reported by clang-tidy.

**Describe the solution you'd like**
Refactor functions to take argument that could be passed by const ref.

**Describe alternatives you've considered**
N/A

**Additional context**
One copy of say SettingsData class might seem insignificant but if it's called 1000 times during program execution. The whole things surely adds some performance overhead. Using clang-tidy we can enhance our code quality and increase performance as well.

**Comment by testitem** [comment]
Hey, I can try to do this

**Comment by testitem** [comment]
wait what why did it unassign ouuan

**Comment by coder3101** [comment]
Sure give it a try. We will suggest changes in PR section of any required. This is also a good way to learn how editor works.

**Comment by testitem** [comment]
What is wrong with the assign system!

**Comment by testitem** [comment]
I will make all the functions in SettingsManager.cpp inlined, as just calling the function incurs a significant overhead if not compiled with -O3.

Furthermore, for one-liner functions, I prefer

```
bool SettingManager::isMaximizedWindow() { return mSettings->value("win_max", "false").toBool(); }
```

instead of

```
bool SettingManager::isMaximizedWindow()
{
    return mSettings->value("win_max", "false").toBool();
}
```

, is that OK?

**Comment by coder3101** [comment]
You can make them inline but don't change formatting. It is there for consistency and better readability

**Comment by coder3101** [comment]
Also You may need to re-format code with clang-format. Using the .clang-format file in root of project

**Comment by ouuan** [comment]
> I will make all the functions in SettingsManager.cpp inlined, as just calling the function incurs a significant overhead if not compiled with -O3.
> 
> Furthermore, for one-liner functions, I prefer
> 
> ```
> bool SettingManager::isMaximizedWindow() { return mSettings->value("win_max", "false").toBool(); }
> ```
> 
> instead of
> 
> ```
> bool SettingManager::isMaximizedWindow()
> {
>     return mSettings->value("win_max", "false").toBool();
> }
> ```
> 
> , is that OK?

I don't think it should be inlined because it's seldom used.

**Comment by coder3101** [comment]
> I don't think it should be inlined because it's seldom used.

Yes exactly, this function is called only once when application launches and then it isn't called. Yet, there is no harm in making it inline. Atleast one `jmp` instruction will be less in assembly.

**Comment by testitem** [comment]
Here's a rule for the source code: **If a class member function is 1 line (e.g. one return statement or one function call) it is inlined and put into the .hpp file, and does not get its own explicit function in the .cpp file.**

**Comment by ouuan** [comment]
But most of these functions are too long to fit in a single line, it's more clear to put all of them in `.cpp` file.

**Comment by testitem** [comment]
"Most"? "Most" of the functions will become this:

`QString getRuntimeArgumentsCpp() { return mSettings->value("runtime_cpp", "").toString(); }`

**Comment by ouuan** [comment]
OK, some of them.

**Comment by ouuan** [comment]
I think it's finished.

**Comment by coder3101** [comment]
@ouuan So it should be closed now
