### ISSUE TITLE
Add a dot at the front of the name of the config file

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#163]
**Is your feature request related to a problem? Please describe.**

I can see the config file in HOME.

**Describe the solution you'd like**

Add a dot at the front of the file name (`.cp_editor_settings.ini`), so that it can be hidden on Linux.

The old config file should be moved to the new path automatically.

**Describe alternatives you've considered**

Save the config file in `QStandardPaths::AppConfigLocation`.

**Additional context**

N/A

**Comment by coder3101** [comment]
@Razdeep take a look at this issue. Beginner friendly and easy.

**Comment by Razdeep** [comment]
@coder310 Thanks for mentioning.

**Comment by coder3101** [comment]
> @coder310 Thanks for mentioning. I will work on it.

We have added this as milestone for 6.0. Implement it ASAP, if you find any issues in implementing, ask in the telegram group!

**Comment by coder3101** [comment]
@Razdeep Are you working on this?

**Comment by Razdeep** [comment]
@coder3101 Yes, I'm working on this

**Comment by coder3101** [comment]
Closed because fixed. Thanks @Razdeep for your contribution
