### ISSUE TITLE
Detached run for Mac OS

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#167]
**Is your feature request related to a problem? Please describe.**

Now detached run is not supported on Mac OS.

**Describe the solution you'd like**

Support detached run on Mac OS

**Describe alternatives you've considered**

N/A

**Additional context**

I can't test on Mac OS, so I can't work on this.

**Comment by coder3101** [comment]
This will take some more time.

**Comment by ouuan** [comment]
@coder3101 OK
