### ISSUE TITLE
Merge input expanding & expected output

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#30]
**Is your feature request related to a problem? Please describe.**

Now input from file and expected output from file are separated, which is not so convenient.

**Describe the solution you'd like**

It would be convenient if they are both in a single pop-up window, which can be opened by clicking the "More" button.

**Describe alternatives you've considered**

Two different buttons for input and expected output. (Now you have to right-click first and then click "Expand" to open the "input from file" window instead of a single click.)

**Additional context**

N/A

**Comment by coder3101** [comment]
Okay, So you want to have `Input From File` button in the popup displayed after user clicks "More" button?

**Comment by ouuan** [comment]
> Okay, So you want to have `Input From File` button in the popup displayed after user clicks "More" button?

Yes.

**Comment by coder3101** [comment]
This should be fairly easy to implement. Isn't it?

> 
> 
> > Okay, So you want to have `Input From File` button in the popup displayed after user clicks "More" button?
> 
> Yes.

**Comment by ouuan** [comment]
close in favor of 63aed67e5175eb2fbbc0d40b39a42076a2d36df5
