### ISSUE TITLE
Add snippet support same as like sublime text

### ISSUE THREAD

**Issue by m3h3d1** [coder3101/cp-editor#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by coder3101** [comment]
Please Let me know how Sublime does it? I have no idea of what you are saying. Please edit your Issue to make it more informative. Thanks!

**Comment by ouuan** [comment]
I'll try to work on it. My plan is a shortcut/hotkey for "use a snippet", then enter the name of the snippet in a pop-up window, then inserted to the code editor.

**Comment by coder3101** [comment]
> I'll try to work on it. My plan is a shortcut/hotkey for "use a snippet", then enter the name of the snippet in a pop-up window, then inserted to the code editor.

Yes you should work on it. I am working on CF-tools integration, so people can submit the code directly from editor and also some other features that are offered by `cf-tools`

**Comment by coder3101** [comment]
This feature has been implement with #75. See it in new CP Editor 5.0
