### ISSUE TITLE
Request for a transparent theme

### ISSUE THREAD

**Issue by ankur314** [coder3101/cp-editor#62]
**Is your feature request related to a problem? Please describe.**
It is not related to a specific problem, just a suggestion to enhance the user interface.

**Describe the solution you'd like**
It would look cool if we had an option to adjust the transparency of the editor.
So requesting a feature to adjust the percentage of transparency of the editor screen (this feature is also implemented in emacs).

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by coder3101** [comment]
This is very specific feature. I will put it to hold unless others request it or we run out of fixing other higher priority and demanding stuffs.

**Comment by ouuan** [comment]
Added in 91d0117.

**Comment by coder3101** [comment]
@ouuan This feature should go into Editor section and not in Extra section of the Editor. Change it

**Comment by coder3101** [comment]
Fixed in 1936c4b

**Comment by ouuan** [comment]
@allcontributors add @ankur314 as a contributor for ideas.
