### ISSUE TITLE
Flexible number of test cases, more than three or only one

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#68]
**Is your feature request related to a problem? Please describe.**

Now there are always three test cases. If the problem has more than 3 test cases, I have to edit them manually, or even frequently (like finally passes test 4 after debugging, but fails on test 1 again, passed test 1 then fails on test 4 again). If the problem has only a single test case, the two empty test cases will cost extra spaces.

**Describe the solution you'd like**

The number of test cases is flexible.

- By default, only one test case.

- A button for adding test cases, another for deleting test cases.

- Auto change after using the competitive companion.

- Use a scroll bar for more than three test cases.

**Describe alternatives you've considered**

Use a drop-down menu instead of the scroll bar for extra test cases.

**Additional context**

N/A

**Comment by coder3101** [comment]
I thought to add it inside tabs but then suppose you need to see the verdict of 3 cases or 4, you need to toggle to all the tabs. It is achievable but i am working on making CF-tools come with Editor so you can submit from the editor itself. After that, i will add this feature too.

**Comment by coder3101** [comment]
@ouuan I don't remember where but somewhere you asked why dark theme was discouraged and no longer available. So first thing is that now you can toggle to editor mode from View, and set any dark editor theme like mokai or drakula. that will make 90% of visible things dark. As for the reason to rmove it, just try the old dark theme on old version. If you toggle it, the editor buttons like dialog box buttons and other widgets will be resized to small sizes. Also, It is not officially supported by windows, in windows only way to get Dark theme is to use UWP apps, which are written by .NET and won;t be cross-platform. Just leave dark theme for some time, When QT supports, it will be automatically done, no worries we only will have to upscale the version. As for why i added it as first because  during development i used it on Plasma desktop on linux, where it looked native and professional, but soon after some days on windows i released it bad so decided to remove it.

**Comment by ouuan** [comment]
> @ouuan I don't remember where but somewhere you asked why dark theme was discouraged and no longer available. So first thing is that now you can toggle to editor mode from View, and set any dark editor theme like mokai or drakula. that will make 90% of visible things dark. As for the reason to rmove it, just try the old dark theme on old version. If you toggle it, the editor buttons like dialog box buttons and other widgets will be resized to small sizes. Also, It is not officially supported by windows, in windows only way to get Dark theme is to use UWP apps, which are written by .NET and won;t be cross-platform. Just leave dark theme for some time, When QT supports, it will be automatically done, no worries we only will have to upscale the version. As for why i added it as first because during development i used it on Plasma desktop on linux, where it looked native and professional, but soon after some days on windows i released it bad so decided to remove it.

I didn't find anything wrong when I was using it. I think a hint like "system-wide dark theme is deprecated" with a link to detailed reasons is better than disabling it.

**Comment by ouuan** [comment]
> I thought to add it inside tabs but then suppose you need to see the verdict of 3 cases or 4, you need to toggle to all the tabs. It is achievable but i am working on making CF-tools come with Editor so you can submit from the editor itself. After that, i will add this feature too.

I think scroll bar or drop-down menu is better than tabs. (If "tabs" means you switch to each case by switching to different tabs, like the code editor.)

By drop-down menu, I mean something like three widgets, each of them has a drop-down menu to choose which test case to display.

**Comment by cs-mshah** [comment]
why can't i run something like hello world and run in the editor itself. What i mean to say is that I should be able to interact and add custom test cases.

**Comment by ouuan** [comment]
> why can't i run something like hello world and run in the editor itself. What i mean to say is that I should be able to interact and add custom test cases.

I don't get your idea, but here are my guesses:

1. By "interact", I guess you want to run the program and type the input by yourself: use detached run, and the shortcut is <kbd>Ctrl+Shift+D</kbd>.

2. "add custom test cases": you CAN edit the inputs:

![screenshot](https://user-images.githubusercontent.com/30581822/72592630-ecfccc00-393d-11ea-893c-cc2cbf8277b4.png)

**Comment by ouuan** [comment]
And I'm really confused by "why can't i run something like hello world and run in the editor itself".

**Comment by cs-mshah** [comment]
I am sorry for my bad way of asking, but what I meant was to run and give input by STDIN.
Thanks for the shortcut, but it says that i need to install xterm. Is it possible to use the gnome-terminal.
And I wanted to know the other shortcuts that are there

**Comment by ouuan** [comment]
> I am sorry for my bad way of asking, but what I meant was to run and give input by STDIN.
> Thanks for the shortcut, but it says that i need to install xterm. Is it possible to use the gnome-terminal.
> And I wanted to know the other shortcuts that are there

Why don't you like xterm? You can install it if you don't have one. Gnome-terminal will only be available for gnome.

You can see the menu for other actions/preferences/shortcuts.

![image](https://user-images.githubusercontent.com/30581822/72608943-c9964900-395e-11ea-859f-0eb6a9ebd0e1.png)

![image](https://user-images.githubusercontent.com/30581822/72608956-cf8c2a00-395e-11ea-8158-3c29677a73fe.png)

You can also set custom hot key for some actions:

![image](https://user-images.githubusercontent.com/30581822/72609008-e6328100-395e-11ea-8bea-1e9e835069f3.png)

**Comment by ouuan** [comment]
Also, I'm working on #82 (put the compiled executable in the same folder as the source file), when I finish that you'll be able to run it in the terminal without compiling it again.

**Comment by ouuan** [comment]
> Gnome-terminal will only be available for gnome.

Sorry for that, I was wrong.

**Comment by ouuan** [comment]
close in favor of 63aed67e5175eb2fbbc0d40b39a42076a2d36df5
