### ISSUE TITLE
Change the name and the description of the repository

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#72]
**Is your feature request related to a problem? Please describe.**

It's already CP Editor 4, but the repo's name is cp-editor2.

There is no "Competitive Programming" but only "CP" in the description, and I can't find this repo by searching "competitive programming editor".

**Describe the solution you'd like**

Change the name of this repo to "CP Editor".

Change the description of this repo to "An editor specially designed for competitive programming".

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
Very good idea. I will change it to CP Editor only. 2 as suffix didn't mentions version rather second repository. I already had CP editor which was first repository for personal use. Now, CP editor 2 is second different repository and older is archived. Any suitable description you would like to add? Mention it and I will change it to that!

**Comment by ouuan** [comment]
I prefer "An editor specially designed for competitive programming" for description. It's briefer.

**Comment by ouuan** [comment]
@coder3101 See <https://travis-ci.org/coder3101/cp-editor>

**Comment by coder3101** [comment]
> https://travis-ci.org/coder3101/cp-editor

It does not matter even if you were to https://github.com/coder3101/cp-editor2 Github will redirect to https://github.com/coder3101/cp-editor (new). So both of the links are true and hence no changes requred. However when travis automatically syncs my account. It will be restored, it does once in 24 hours.
