### ISSUE TITLE
Make a telegram group / Github organization

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#78]
**Is your feature request related to a problem? Please describe.**

There are always discussions not related to the issues/PRs.

**Describe the solution you'd like**

Make a telegram group / Github organization for discussions.

A telegram group may be a better choice because it can be open for the users.

Of course, you can make both of them. And this repo could be transfered to the organization.

In one word, build a community from now on. Though there are only two active contributors now. Hope there will be more in the future.

**Describe alternatives you've considered**

Use other platforms.

**Additional context**

N/A

**Comment by coder3101** [comment]
Let's create a telegram group and then I will update all of my blogs with the link to join the group. Nice idea, as for the github organization, I will create it only after i see good response on telegram group. Thanks for this idea by the way!

**Comment by coder3101** [comment]
https://t.me/cpeditor
