### ISSUE TITLE
Setting for clang-format

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#81]
**Is your feature request related to a problem? Please describe.**

It's not convenient to set a custom style for clang-format now.

**Describe the solution you'd like**

You can edit `.clang-format` file for CP Editor in the preference window.

You can also choose to use the `.clang-format` file corresponding to the file path.

**Describe alternatives you've considered**

N/A

**Additional context**

I'll try to implement it tomorrow.

**Comment by coder3101** [comment]
If you can come up with something better than this. All good, as for now to use custom formatting we have to do this : change compile command to `clang-format -i -style=<absolute_path_to_custom_file>`

**Comment by ouuan** [comment]
> If you can come up with something better than this. All good, as for now to use custom formatting we have to do this : change format command to `clang-format -i -style=<absolute_path_to_custom_file>`

Does it really work? See <https://stackoverflow.com/questions/46373858/how-do-i-specify-a-clang-format-file> and I've tried it myself.

**Comment by ouuan** [comment]
I'll implement clang-format settings in the preference window, and `--cursor` support and format selection only if there is a selection.

**Comment by coder3101** [comment]
Okay, As you like it. I will work on new Editor. Also I am about to release 5.0.2 (next release), it has some editor fixes (from upstream). You should too propose some PR which you wish should go in next release. You have exactly 2 hours from the time, i post this. If you do not want to add something, ignore this message.

**Comment by ouuan** [comment]
I think my next PR will be on tomorrow.
