### ISSUE TITLE
Put the compiled executable in the same folder as the source file

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#82]
**Is your feature request related to a problem? Please describe.**

> Any decent antivirus scans just-made executables, so every time I compile it scans the .exe, which means I have to wait 10 seconds before it can actually run. Every single time I compile. The thing is, you can add an exception in the antivirus, but I'd prefer not adding an exception in my damn AppData folder!

**Describe the solution you'd like**

> Put the .exe in the same folder as the source file.

**Describe alternatives you've considered**

> At least let us choose where it should be.

**Additional context**

Originally aked [here](http://codeforces.com/blog/entry/71907?#comment-562850).

**Comment by ouuan** [comment]
Also, I suggest using [QTemporaryFile](https://doc.qt.io/qt-5/qtemporaryfile.html) instead of `Base::Files`. `Base::Files` and `MainWindow::windowIndex` can be got rid of completely. Not only because it's more convenient and safe, the current solution is bad also because of the window index changes after closing/moving tabs.

I'd like to implement this after #96 and #97.

**Comment by ouuan** [comment]
For self reminding: use `waitForFinished()` instead of `waitForStarted()` to get rid of unnecessary `kill()` and the warning message `QProcess: Destroyed while process ("g++") is still running.`.

**Comment by ouuan** [comment]
I'd like to implement #92 first now. Reimplement compiler/runner/cf-tool is a big work, since I need to keep the temporary file in order to reuse the executable files, and I need to use different logic for untitled tabs, saved files, unsaved files with a filePath, save error, etc.

**Comment by ouuan** [comment]
But I'll be thinking of "how to restore the window index" when I work on hot exit...

Seems that this issue is really a dependency of #92.

**Comment by ouuan** [comment]
What about only reuse executable files if the source file is saved? That will make things easier because I can delete all temporary files right after using them.

**Comment by coder3101** [comment]
Yes that would be nice tok
