### ISSUE TITLE
Choice to disable companion tab

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor#83]
**Is your feature request related to a problem? Please describe.**

I'd like to use competitive companion in the way of 25996d8, but I'm forced to make a "companion tab" now.

**Describe the solution you'd like**

Add a choice of enable cf-tool (companion tab) or not in the settings.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
I get it. You wanted to that your currently opened tab change to companion tab. It will be good but if you parse a complete contest the only way to achieve or handle such parsing of companion data is if we open a new tab for each data we recieved. However, I can add an option for your type of behavior.

As for the enable and disable thing, Competitive companion has it but CF tool doesn't. I will add it soon.
