### ISSUE TITLE
Make the test case textboxes narrower, or allow resizing

### ISSUE THREAD

**Issue by testitem** [coder3101/cp-editor#88]
**Is your feature request related to a problem? Please describe.**
Currently, the window won't fit on my screen.

**Describe the solution you'd like**
Optimally, I'd like the input/output boxes as well as the error boxes to be as tiny as possible (they definitely don't need to be that big)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ouuan** [comment]
I'll look into it. Now you can use editor mode / IO mode as a work-around.

![image](https://user-images.githubusercontent.com/30581822/72200240-fc819e00-3481-11ea-9335-8fc6049a705f.png)

**Comment by coder3101** [comment]
Yes, now you can change view to Editor mode and those input and error box will go away, giving you full editor to type one. If you find that it solves your issue, close it.

**Comment by ouuan** [comment]
I also think the minimum width for the IO part is too big.

**Comment by ouuan** [comment]
I don't know why, but even in the editor mode / IO mode, the whole window can't be resized to smaller than split mode.

**Comment by coder3101** [comment]
> I don't know why, but even in the editor mode / IO mode, the whole window can't be resized to smaller than split mode.

Correct, #93 is a proof of this behavior. I will see to it, seems like some sizePolicy is set to higher minimum value.

**Comment by testitem** [comment]
Right now the textboxes are disgraciously big. They can be shrunk to 1/6 or 1/10 of their current size without affecting the UI.

**Comment by coder3101** [comment]
Yes they can be. Be sure this will be done soon.

**Comment by testitem** [comment]
"done soon"

**Comment by coder3101** [comment]
The editor now can get this small, even will fit on 200x300 pixel displays.
![img](https://i.imgur.com/IGHkaku.jpg)

Input boxes can get very narrow now. Just see!
![img](https://i.imgur.com/SCYPeKQ.jpg)

**Comment by coder3101** [comment]
Fixed in 8772da7
