### ISSUE TITLE
Support of Hot Exit

### ISSUE THREAD

**Issue by m3h3d1** [coder3101/cp-editor#92]
**Is your feature request related to a problem? Please describe.**
CP-Editor doesn't remember the previous session.

**Describe the solution you'd like**
Enable the editor to exit immediately without prompting, preserving changes and unsaved files for the next time it is run. When the CP-Editor is launched again, all opened and edited files will be at the same state as they were before close. 
N.B: VS Code, Sublime Text supports hot exit.

**Describe alternatives you've considered**
If it is hard to code "Hot Exit" then firstly add support of remembering the previous tabs opened earlier. 

**Additional context**
N/A

**Comment by coder3101** [comment]
@ouuan  need your comments here. It is easy to implement maybe you could guide someone here.

**Comment by ouuan** [comment]
Should I guide him to make a PR?

**Comment by ouuan** [comment]
I'd like to implement it myself though.
