### ISSUE TITLE
Not able to resize the editor on ubuntu 18.04

### ISSUE THREAD

**Issue by xX-B1nary-Xx** [coder3101/cp-editor#93]
I dont know why i can't resize the editor there is no option to maximize.[Photo](https://ibb.co/jz8WVvJ)

**Comment by coder3101** [comment]
Thank you for reporting it. Your screen size is not big enough to accommodate the complete window and hence it couldn't be maximised. We are working on a fix for this. Its an indirect consequences of #88 @ouuan could you please look at it. It seems related with sizePolicy of IO mode.

**Comment by ouuan** [comment]
> Thank you for reporting it. Your screen size is not big enough to accommodate the complete window and hence it couldn't be maximised. We are working on a fix for this. Its an indirect consequences of #88 @ouuan could you please look at it. It seems related with sizePolicy of IO mode.

I've tried change the sizePolicy, and it's very confusing.Like if I change "minimum" to "expand", the window is not maximized in a new session.  I'm not familiar with UI, could you have a try first?

**Comment by xX-B1nary-Xx** [comment]
> Thank you for reporting it. Your screen size is not big enough to accommodate the complete window and hence it couldn't be maximised. We are working on a fix for this. Its an indirect consequences of #88 @ouuan could you please look at it. It seems related with sizePolicy of IO mode.

Thanks for your reply. A lot of laptops available in the market majority of them are 13-inch laptop like mine. So it's a standard one. Did you build this assuming that this will be used only on desktop monitors?

**Comment by coder3101** [comment]
No such assumption were made. I will see to it and make it work.

**Comment by coder3101** [comment]
> Edit: I tried this on windows and it works fine. The windows fit on my screen.

Clearly it means that it could be due to hi-scaling set on ubuntu. Or if not ubuntu it could be some other issues related with ubuntu's window manager. If this were to be really related with Sizes, which you can confirm by setting display scaling to >100%, the new scaling should fix it, otherwise if its not related, the issue will persist. Another way to confirm this would be to project your ubuntu on to a TV or monitor and see if maximize button comes, if it comes then it was size issue other-wise some issue related with ubuntu's window that is not allowing it to scale. **It would be good, if some other ubuntu users on 13 laptop's could confirm this behavior.**

As far as design goes, the editor (code editor) must occupy 500 pixels in width and remaining occupies minimum they want to occupy. So it can't be minimized beyond that sizes.

**Comment by Saurav-Paul** [comment]
I am facing the same issus.. I am using mint Linux. My screen size   is 16 inch.. But it not fitting perfectly😐

**Comment by ouuan** [comment]
> I am facing the same issus.. I am using mint Linux. My screen size is 16 inch.. But it not fitting perfectly

What's your screen resolution?

**Comment by coder3101** [comment]
Yes as pointed by @ouuan this depends not on your screen size but pixels (resolutions). A bigger display with lower resolution or scaling can result this. At the same time, i am aware of the ugly size of boxes. I wish to fix them this weekend.

**Comment by coder3101** [comment]
The editor now can get this small, even will fit on 200x300 pixel displays.
![img](https://i.imgur.com/IGHkaku.jpg)

Input boxes can get very narrow now. Just see!
![img](https://i.imgur.com/SCYPeKQ.jpg)

@xX-B1nary-Xx  This new editor with this change is in dev branch and in some days it will make its way to stable and when it does please try and it it did not worked for you. Reopen this issue

**Comment by xX-B1nary-Xx** [comment]
> The editor now can get this small, even will fit on 200x300 pixel displays.
> ![img](https://camo.githubusercontent.com/a5c20066fca93087432911099a99b2ba44b4b468/68747470733a2f2f692e696d6775722e636f6d2f4947486b616b752e6a7067)
> 
> Input boxes can get very narrow now. Just see!
> ![img](https://camo.githubusercontent.com/6521b2d6ea09fcf966aaa023c885fb208179c2dc/68747470733a2f2f692e696d6775722e636f6d2f53435950654b512e6a7067)
> 
> @xX-B1nary-Xx This new editor with this change is in dev branch and in some days it will make its way to stable and when it does please try and it it did not worked for you. Reopen this issue

Thank you for this :)

**Comment by coder3101** [comment]
Fixed in 8772da7

**Comment by coder3101** [comment]
> Thank you for this :)

Always welcome random user! ;-P

**Comment by ouuan** [comment]
@allcontributors add @1CH1GO as a contributor for bug report.
